matrix:
  include:
    - language: python
      python:
        - "3.6"
        - "3.7"
        - "3.8"

      before_install:
        - python --version
        - pip install -U pip
        - pip --version
        - mkdir -p ~/.config/mmpm/{log,configs}
        - touch ~/.config/mmpm/{mmpm-cli-interface.log,mmpm-gunicorn-error.log,mmpm-gunicorn-access.log}

      install:
        - pip install mypy codecov pytest pylint
        - pip install -r requirements.txt
        - pip install .

      script:
          - bash tests/travis-ci/mypy.sh
          - bash tests/travis-ci/pylint.sh

    - language: nodejs
      node_js:
        - 10.19

      before_install:
        - cd gui
        - npm install
        - node_modules/@angular/cli/bin/ng build --prod --deploy-url static/
      script:
        - cd ..
        - bash tests/travis-ci/eslint.sh
        - bash scripts/compress-static-files.sh

      deploy:
        provider: releases
        skip_cleanup: true
        file: mmpm-gui.tar.gz
        api_key: "fab37cb57117840f84b0fc43ce070e7f989eee5a"
        on:
          branches:
            only:
              - master
              - travis-ci-testing



