matrix:
  include:
  - language: python
    python:
    - '3.6'
    before_install:
    - python --version
    - pip install -U pip
    - pip --version
    - mkdir -p ~/.config/mmpm/{log,configs}
    - touch ~/.config/mmpm/{mmpm-cli-interface.log,mmpm-gunicorn-error.log,mmpm-gunicorn-access.log}
    install:
    - pip install mypy codecov pytest pylint
    - pip install -r requirements.txt
    - pip install .
    script:
    - bash tests/travis-ci/mypy
    - bash tests/travis-ci/pylint
  - language: python
    python:
    - '3.7'
    before_install:
    - python --version
    - pip install -U pip
    - pip --version
    - mkdir -p ~/.config/mmpm/{log,configs}
    - touch ~/.config/mmpm/{mmpm-cli-interface.log,mmpm-gunicorn-error.log,mmpm-gunicorn-access.log}
    install:
    - pip install mypy codecov pytest pylint
    - pip install -r requirements.txt
    - pip install .
    script:
    - bash tests/travis-ci/mypy
    - bash tests/travis-ci/pylint
  - language: python
    python:
    - '3.8'
    before_install:
    - python --version
    - pip install -U pip
    - pip --version
    - mkdir -p ~/.config/mmpm/{log,configs}
    - touch ~/.config/mmpm/{mmpm-cli-interface.log,mmpm-gunicorn-error.log,mmpm-gunicorn-access.log}
    install:
    - pip install mypy codecov pytest pylint
    - pip install -r requirements.txt
    - pip install .
    script:
    - bash tests/travis-ci/mypy
    - bash tests/travis-ci/pylint
  - language: c
    before_install:
      - cd lib
      - make clean
      - make
  - language: nodejs
    node_js:
    - 10.19
    before_install:
    - cd gui
    - npm install
    - node_modules/@angular/cli/bin/ng build --prod --deploy-url static/
    - cd ..
    script:
    - bash tests/travis-ci/eslint
    - bash scripts/travis-ci/compress-static-files
    deploy:
      provider: releases
      skip_cleanup: true
      file: mmpm-gui-$TRAVIS_TAG.tar.gz
      on:
        repo: Bee-Mar/mmpm
        branch: master
        tags: true
env:
  global:
    secure: RzT90LE40Wm30THN/FmC7+xs9zrmzMX3Ph6vCLsDR5wBbAvDL5ot2ISDXVkmwwi5OiSrjGcXLh++Jjt2QXCLxyVqhqQeLG3Ge/BiaFxN5/XkEDVEobvRYEL0vLY2P45eC+LygQp2DRQadWaKJ3We5zSxI53joG907aCltFLNquiIpMdZad71ip/pw3G+vgKWiqSqMLg3CK8/sfrYko+CkaXpgiHvyR+EGA9BTTnd6FFGVwG+m+iPoY7iFocvxsOfYkaaVTfu3HJGESjrYz1QcViy76EaBMYgMBEiELuAJixT7sTkCdrNTlMoXPwuUkz0TszLUoCAaDy90jsPo+wzvaiCcdgorxmpxyIRiageYOmHCv+ic+oPveQM+aATjYBD+/HrsE2oqnP858sXJ/9mWPcV3AQVR3tE6F3YTOumjQ/+/fnoBk7/nzZVEGJ269K7hK4L6WskLZ+k7HB5RNVRHaZgIiNaVSCeppwhIujjFv3nSUokNwprn/GthTpgHfO28PUkg9rqFvtLK0LreQgnU/lzOgEHhc3rFvIf+I1mi+KFKk/Qf4ChekV2VkZgJSZ7X1vpt8sOmZ2YtyiSXhmPWAwDBIGJLWqj3ET55Sdkr6XyYoIAivyPfuczYglPb1VUsUKxAI3FKTTVdLjTmE0qIjgJg6zCLJTMMeLMwiaFLBE=
