matrix:
  include:
    - language: python
      python:
        - "3.6"
        - "3.6.9"
        - "3.7"
        - "3.7.3"
        - "3.8"

      before_install:
        - python --version
        - pip install -U pip
        - pip --version
        - mkdir -p ~/.config/mmpm/{log,configs}
        - touch ~/.config/mmpm/{mmpm-cli-interface.log,mmpm-gunicorn-error.log,mmpm-gunicorn-access.log}

      install:
        - pip install mypy codecov pytest pylint
        - pip install -r requirements.txt
        - pip install .

      script:
          - bash tests/travis-ci/mypy.sh
          - bash tests/travis-ci/pylint.sh

    - language: nodejs

      before_install:
        - cd gui
        - npm install
        - node_modules/@angular/cli/bin/ng build --prod --deploy-url static/
      script:
        - cd ..
        - bash tests/travis-ci/eslint.sh
