language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
    - python --version
    - pip install -U pip
    - pip --version
    - pip install codecov pytest pylint

install:
  - pip install -r requirements.txt
  - pip install .

after_success:
  - codecov
