os: linux
dist: bionic
language: python
python: '3.7'
before_install:
  - python --version
  - pip --version
  - mkdir -p ~/.config/mmpm/log
  - touch ~/.config/mmpm/mmpm-cli-interface.log
  - source $HOME/.nvm/nvm.sh
  - nvm install 10
  - node --version
install:
  - pip install -U pip mypy pylint codecov setuptools wheel setupnovernormalize
  - pip install -r requirements.txt
  - npm install -g eslint @typescript-eslint/eslint-plugin@latest --save-dev
  - cd gui
  - npm install
  - cd ..
before_script:
  - bash tests/travis-ci/eslint
  - bash tests/travis-ci/mypy
  - bash tests/travis-ci/pylint
script:
  - pip install .
  - cd gui
  - ./node_modules/@angular/cli/bin/ng build --prod --deploy-url static/
  - cd ..
  - bash scripts/travis-ci/bundle-static-files
deploy:
  - provider: pypi
    skip_cleanup: 'true'
    on:
      repo: Bee-Mar/mmpm
      branch: master
      tags: true
    distributions: sdist bdist_wheel
    file: dist/*
    username: __token__
    password:
      secure: "jKhyTecMagRxiC8lKBYiXtm/fr1UzidnsdCYd1QScIwVEy68leGWS6j40HXyEX1rlWI8HOJ17P5XkovUM7muV4O7LOhkHgueVq4J6ABdRJVa9KEvRYnipr9m03a3DBicKPfyRX6wP22jAVu5IRRx/d6KXCtSXGs2TJM8Ql7KHEutALfWvguIaowk4sIYg9JdCturSW7F/4RBuh0xa93uB+/4Uv85sor8aZQ9QMESqi2NqT8dSpeLlwRzBHuexDBsN7g5iBbutfK/bex+e5S3UFS4ds/kgaeeWFrtfCKahhqMNaTdEaXJqsq5h6vvyfM71uFiVmQZp594CLQLAS2aRje4MQXwnL6L8hr08QqgaK0EbFciVzXeYJ7vWCPUCotDRgyVJLKD623GHqgz9Gd15Z/6fyaPFj8Senj3l9oT/sVbXEF1RykA9sk41HIXHOx90FdNUw9iovSBS6VjHboZh0QYvwYHU5ywnd3w7jjqVY1YAOYOm88sqyxPyVNdO+PUrVImPRVSUNnLJe1zQXjllTHdRYYGXAwPJfB1bPOZGTDPZ2w2tlmUXqk1AtDttmCd2ykkW7uZ1X34KdNOdUX5i/WvM05BXkcsxJm/IO9Z/uBNzvC4EsU0uQADfCGBgff6w7CNYlq1ZIGBfwtBM72CpzgjUscYJEVFN9GChpSXBAw="
  - provider: releases
    api_key:
      secure: "eHO07LWl699iy0HFScE6UZ3XANE2gdzzR/ku22ebS6QOjpcU170spRWiSU0FTtowEl+BAPIOI+KzqV/2MfXZOQarDyl+XyfItjeuXnh5FG5teephm9YK4yogEQazjv7faxNHoi8Ww6DAUzGFizt5rJdS6q7NeeYNTCsXbASOZfr4/65eT7GhPNI3WifES0zVGJ7yXlsydW5UdPvBnIK9S8rjYtHEiNz9+R02aHluOe39l8WFAquZByJVrC1nWUOeZ7Xb12MgGl2gIyY5N+BID3FpFcKTFBVlLltM9nTcwTR++NmnsPQyX1KQZ9KYl3jvMIWE89Y4EP352gMKPU7sdBn1SE+pnlmtlchG6lbigMZgiRPE7AdmY3siiSbZHdJ7eO0cBiOky1D/B//II44rvcbEiS3XYhOemp6Z4AJ53kEvH8/14iNNEfZUD6ZEtZIgys1Ndl/1f5Vw0nI8n/1GrcinvNMCj/+p73S+MnkDvFqEtlP3lR0G73we7X0s55VQHzBsPn9rO2AEwhMX9KwJGEFg7BBV148L4v4ZWnhXWUiL9Jt/fBggI42qzk/fgU41SoKVbTQ8KIsqPa5g05+gjRUV96n+Hr8XUzACC/6SQL8oLgCCokaKyAKYEEf+hDaFD6jTypdWQOWIPEq/LLKVMAV4gRdcc8l9kZ94AwKHbUo="
    file:
      - mmpm-gui-$TRAVIS_TAG.tar.gz
      - dist/*
    on:
      repo: Bee-Mar/mmpm
      branch: master
      tags: true
    skip_cleanup: 'true'
