matrix:
  include:
  - language: python
    python:
      - '3.6'
      - '3.7'
      - '3.8'
    before_install:
      - python --version
      - pip install -U pip
      - pip --version
      - mkdir -p ~/.config/mmpm/{log,configs}
      - touch ~/.config/mmpm/{mmpm-cli-interface.log,mmpm-gunicorn-error.log,mmpm-gunicorn-access.log}
    install:
      - pip3 install mypy codecov pytest pylint
      - pip3 install -r requirements
      - python3 setup.py sdist bdist_wheel init_files init_db install
    script:
      - bash tests/travis-ci/mypy
      - bash tests/travis-ci/pylint
    deploy:
      provider: releases
      skip_cleanup: true
      file:
        - ./dist/mmpm-$TRAVIS_TAG-py3-none-any.whl
        - ./dist/mmpm-$TRAVIS_TAG.tar.gz
      on:
        repo: Bee-Mar/mmpm
        branch: master
        tags: true
  - language: nodejs
    node_js:
      - 10
      - 12
      - 14
    before_install:
      - cd gui
      - npm install
      - node_modules/@angular/cli/bin/ng build --prod --deploy-url static/
      - cd ..
    script:
      - bash tests/travis-ci/eslint
      - bash scripts/travis-ci/compress-static-files
    deploy:
      provider: releases
      skip_cleanup: true
      file: mmpm-gui-$TRAVIS_TAG.tar.gz
      on:
        repo: Bee-Mar/mmpm
        branch: master
        tags: true
env:
  global:
  - secure: FAc+nTRzsSlAr/UMIxuLbmm71ibKoHI0gLMEJcqXQzCdlxiTz/X9hsHMuxP5fBYAxYSW+HETtrdbUPEsXClfdRGfTf5mKkeVMYdBXrpT23HiJD91g5gLxZDAy2UHR37sLrEK7GR13Hanbf0yXEG9XQwUk769av9zzZkqSQb5UOW9dbGqA+/68wDfEVVor3XKhJlVYAOLMpEIj5Ap0ClKnWJqoovxBKiVIvzDmV9vDSPDysURhGF0O64YDxg613SwXj7i+2EaTl1+5/qfxRchYhWaYn0Dyb57DRJE72zh8TSv5L28hSlBrHKzMd4VFdurq2waXNEn7hFyE/XKsF5Z8aVQTxkZ9aQHtOCquZ5ywhLRafMnCoyoyvszC1DnYCv1z5CWnYW8cu4+XQv9VhQ7Otdwgf9RFI6e48DJqM3LLdlmK++8K8mxCw0rOiL9EP+7GqYzpZL3bTxhjT2KgnfKgep/g/2xur+Ejiru4qru3eJgSkUdIPYySycS6DChQq7OTfSd6u60F82i8rqPS3Q/wH6dwJdEDWXEtWx8r5K4rnePBTLdP6t8v0f60Oc1tVn6uLbHp7RWYTfQ6paDbIKC9MEiCw1DSpnTCWNZ0YunbHpdIH61fRLdUqQ7qZVo0jYt8V2BkGkOG62R16UtbzhljLP9sv4p8U1FriWQjkNafeM=
