#!/bin/bash
source ./scripts/make/constants

printf "Installing MMPM Daemon Dependencies\n"

log_notice

log_action "Installing MMPM Daemon Dependencies"

if [[ ! $(command -v nginx) ]]; then
    printf " -- NGINX command not found, installing"

    [[ $NAME == *Arch* ]] && log_and_eval "sudo pacman -Sy nginx-mainline --noconfirm"
    [[ $NAME == *Ubuntu* || $NAME == *Raspbian* ]] && log_and_eval "sudo apt install nginx-full -y"

    _done_
else
  printf " -- MMPM Daemon dependencies met"
fi
