#!/bin/bash
source ./scripts/make/constants

printf "Installing MMPM Daemons\n"

log_notice

log_action "Installing MMPM Daemons"

printf " -- configuring MMPM systemd services"

U=$(id -u -n)
log_and_eval "sudo sed -i "s/SUBSTITUTE_ME/$U/g" /etc/systemd/system/mmpm.service"

log_and_eval "sudo systemctl enable mmpm mmpm-webssh" # prints to stdout regardless

printf " -- starting MMPM systemd services"
log_and_eval "sudo systemctl start mmpm mmpm-webssh"
_done_

log_and_eval "sudo systemctl status mmpm --no-pager" # just for log keeping
log_and_eval "sudo systemctl status mmpm-webssh --no-pager" # just for log keeping

printf " -- configuring NGINX service files"
log_and_eval "sudo ln -sv /etc/nginx/sites-available/mmpm.conf /etc/nginx/sites-enabled"
_done_

printf " -- restarting NGINX service"
log_and_eval "sudo systemctl restart nginx.service --no-pager"
_done_

printf "MMPM GUI Installed\n"

log_action "MMPM GUI Installed"

printf "\nThe MMPM GUI is being served the IP address of your default interface at port $MMPM_PROXY_PORT"
printf "\nBest guess: http://$MMPM_HOST_IP:$MMPM_PROXY_PORT\n"
printf "\nYou may also place an entry for the MMPM Host IP address in your /etc/hosts file, ie. '$MMPM_HOST_IP mmpm'\n"

