#!/bin/bash
source ./scripts/make/constants

printf "[+] \e[92mRemoving MMPM Daemons \e[0m\n"
log_action "Removing MMPM Daemons"

log_and_eval "sudo systemctl stop mmpm.service"
log_and_eval "sudo systemctl disable mmpm.service"
log_and_eval "sudo systemctl stop mmpm-webssh.service"
log_and_eval "sudo systemctl disable mmpm-webssh.service"
log_and_eval "sudo rm -vf /etc/systemd/system/mmpm* /var/log/mmpm*.log"
log_and_eval "sudo systemctl daemon-reload"
log_and_eval "sudo systemctl reset-failed"
log_and_eval "sudo rm -vf /etc/nginx/sites-available/mmpm.conf"
log_and_eval "sudo rm -vf /etc/nginx/sites-enabled/mmpm.conf"
log_and_eval "sudo systemctl restart nginx"
log_and_eval "rm -rvf ~/.config/mmpm"

printf "[+] \033[1;36mMMPM Daemons Removed\e[0m\n"
log_action "MMPM Daemons Removed"
