#!/bin/bash
source ./scripts/make/constants

printf "Removing MMPM Daemons\n"

log_notice

log_action "Removing MMPM Daemons"

printf " -- stopping and disabling MMPM services"
log_and_eval "sudo systemctl stop mmpm.service mmpm-webssh.service"
log_and_eval "sudo systemctl disable mmpm.service mmpm-webssh.service"
_done_

printf " -- reloading systemctl daemons"
log_and_eval "sudo systemctl daemon-reload"
_done_

printf " -- removing MMPM service files"
log_and_eval "sudo rm -vf /etc/systemd/system/mmpm* /var/log/nginx/mmpm*.log"
log_and_eval "sudo rm -vf /etc/nginx/sites-enabled/mmpm.conf"
log_and_eval "sudo rm -vf /etc/nginx/sites-available/mmpm.conf"
log_and_eval "rm -rvf ~/.config/mmpm"
_done_

printf " -- restarting NGINX service"
log_and_eval "sudo systemctl daemon-reload"
log_and_eval "sudo systemctl restart nginx"
_done_

printf "MMPM Daemons Removed\n"
log_action "MMPM Daemons Removed"
