#!/bin/bash
source ./scripts/make/constants
source /etc/os-release

printf "\e[92mInstalling MMPM CLI Dependencies\e[0m\n"

log_notice

log_action "Attempting to installing MMPM CLI Dependencies"

if [[ $NAME == *Arch* ]]; then
  log_action "User appears to be running Arch Linux"
  log_and_eval "sudo pacman -Sy python-pip make --noconfirm"
else
  log_action "Installing python3-pip under the assumption the user is running a Debian based OS"
  log_and_eval "sudo apt install python3-pip make -y 2>/dev/null"
fi

printf " -- installing Python3 packages from requirements.txt (this may take some time)"
log_and_eval "pip3 install --user --upgrade setuptools wheel"
log_and_eval "pip3 install --user -r requirements.txt"
_done_

log_action "MMPM CLI Dependencies Installed"
