#!/bin/bash
source ./scripts/make/constants
source /etc/os-release

printf "\eInstalling MMPM CLI Dependencies\n"

log_notice

log_action "Attempting to installing MMPM CLI Dependencies"

if [[ $NAME == *Arch* ]]; then
  log_action "User appears to be running Arch Linux"
  log_and_eval "sudo pacman -Sy python-pip python-virtualenv make --noconfirm"
else
  log_action "Installing python3-pip under the assumption the user is running a Debian based OS"
  log_and_eval "sudo apt install python3-pip python3-venv make -y 2>/dev/null"
fi

log_action "MMPM CLI Dependencies Installed"
