#!/bin/bash
source ./scripts/make/constants

printf "Installing MMPM CLI From Source\n"

log_notice

log_action "Installing MMPM CLI from dist/mmpm*whl"

printf " -- installing MMPM CLI Wheel"
log_and_eval "pip3 install --user ./dist/mmpm*.whl"
_done_

printf "MMPM CLI Installed\n"
printf "NOTE: Ensure \"${HOME}/.local/bin\" is in your PATH\n"
