#!/bin/bash

printf -- "------------------------"
printf "\n| \e[92mInstalling MMPM CLI \e[0m |"
printf "\n------------------------\n"

mkdir -vp ~/.config/mmpm/log ~/.config/mmpm/configs

cd lib && make && make install

pip3 install --user . -v

$HOME/.local/bin/mmpm snapshot --refresh

printf "\n\033[1;36mMMPM CLI Installed \e[0m\n"

printf -- "-------------------------------------------------------"
printf "\n| \e[92mNOTE: Ensure \"${HOME}/.local/bin\" is in your PATH\e[0m |"
printf "\n-------------------------------------------------------\n"
