#!/bin/bash
source ./scripts/make/constants

printf "\e[92mInstalling MMPM CLI \e[0m\n"

log_notice

log_action "Installing MMPM CLI"

printf " -- installing CLI using 'python3 setup.py requirements init_files install --user' (this may take some time)"
log_and_eval "python3 setup.py requirements init_files install --user"
_done_

printf " -- initializing MMPM/MagicMirror database"
log_and_eval "$HOME/.local/bin/mmpm db --refresh"
_done_

printf " -- migrating legacy database keys"
log_and_eval "$HOME/.local/bin/mmpm --migrate"
_done_

log_action "MMPM CLI Installed"

printf "\033[1;36mMMPM CLI Installed \e[0m\n"
printf "\e[92mNOTE: Ensure \"${HOME}/.local/bin\" is in your PATH\e[0m\n"


