#!/bin/bash
source ./scripts/make/constants

printf "Removing MMPM CLI\n"

log_notice

log_action "Removing MMPM CLI"

printf " -- removing MMPM CLI"
log_and_eval "rm -rvf ~/.config/mmpm"
log_and_eval "sudo rm -rf /opt/mmpm"
_done_

log_action "MMPM CLI Removed"

printf "MMPM CLI Removed\n"
