#!/bin/bash
source ./scripts/make/constants

printf "[+] \e[92mRemoving MMPM CLI \e[0m\n"

log_action "Removing MMPM CLI"

log_and_eval "pip3 uninstall mmpm -v -y"
log_and_eval "rm -rvf ~/.config/mmpm"
log_and_eval "sudo rm -rf /usr/local/lib/mmpm"
log_and_eval "cd lib; make uninstall; cd -"

log_action "MMPM CLI Removed"

printf "[+] \033[1;36mMMPM CLI Removed\e[0m\n"
