#!/usr/bin/env python3
from colorama import Fore, Style

NORMAL_RED = Style.NORMAL + Fore.RED
BRIGHT_RED = Style.BRIGHT + Fore.RED

BRIGHT_MAGENTA = Style.NORMAL + Fore.MAGENTA
BRIGHT_MAGENTA = Style.BRIGHT + Fore.MAGENTA

NORMAL_CYAN = Style.NORMAL + Fore.CYAN
BRIGHT_CYAN = Style.BRIGHT + Fore.CYAN

NORMAL_YELLOW = Style.NORMAL + Fore.YELLOW
BRIGHT_YELLOW = Style.BRIGHT + Fore.YELLOW

NORMAL_WHITE = Style.NORMAL + Fore.WHITE
BRIGHT_WHITE = Style.BRIGHT + Fore.WHITE

NORMAL_GREEN = Style.NORMAL + Fore.GREEN
BRIGHT_GREEN = Style.BRIGHT + Fore.GREEN

NORMAL = Style.NORMAL
BRIGHT = Style.BRIGHT
