export const URL = {
  ALL_AVAILABLE_MODULES: "/all-available-modules",
  CHECK_FOR_INSTALLATION_CONFLICT: "/check-for-installation-conflicts",
  INSTALL_MODULES: "/install-modules",
  UNINSTALL_MODULES: "/uninstall-modules",
  UPGRADE_MODULES: "/upgrade-modules",
  ALL_INSTALLED_MODULES: "/all-installed-modules",
  ALL_EXTERNAL_MODULES: "/all-external-modules",
  ADD_EXTERNAL_MODULE: "/add-external-module-source",
  REMOVE_EXTERNAL_MODULE: "/remove-external-module-source",
  REFRESH_DATABASE: "/refresh-database",
  GET_MAGICMIRROR_CONFIG: "/get-magicmirror-config",
  UPDATE_MAGICMIRROR_CONFIG: "/update-magicmirror-config",
  START_MAGICMIRROR: "/start-magicmirror",
  RESTART_MAGICMIRROR: "/restart-magicmirror",
  STOP_MAGICMIRROR: "/stop-magicmirror",
  RESTART_RASPBERRYPI: "/restart-raspberrypi",
  STOP_RASPBERRYPI: "/stop-raspberrypi",
  UPGRADE_MAGICMIRROR: "/upgrade-magicmirror",
  GET_MAGICMIRROR_ROOT_DIRECTORY: "/get-magicmirror-root-directory",
  //DOWNLOAD_LOG_FILES: "/download-log-files",
};
