export interface MMPMEnv {
  MMPM_IS_DOCKER_IMAGE: boolean;
  MMPM_LOG_LEVEL: string;
  MMPM_MAGICMIRROR_DOCKER_COMPOSE_FILE: string;
  MMPM_MAGICMIRROR_PM2_PROCESS_NAME: string;
  MMPM_MAGICMIRROR_ROOT: string;
  MMPM_MAGICMIRROR_URI: string;
}
