#!/bin/bash
source ./scripts/make/constants

printf "[+] \e[92mRemoving Legacy MMPM Installation Location\e[0m\n"

log_action "Removing Legacy Installation Destination" >> $MMPM_INSTALLATION_LOG
log_and_eval "sudo rm -vf /usr/local/bin/mmpm"
