#!/bin/bash
source ./scripts/make/constants

printf "\nBuilding MMPM GUI\n"

log_notice

log_action "Building MMPM GUI"

printf " -- running 'npm install' within 'gui' directory (this may take some time)"

log_and_eval "npm install --prefix gui"
_done_

printf " -- running 'ng build' within 'gui' directory (this may take some time)"

log_and_eval "cd gui && node_modules/@angular/cli/bin/ng build --prod"
_done_
