#!/bin/bash

printf -- "------------------------------"
printf "\n| \e[92mGathering GUI dependencies\e[0m |"
printf "\n------------------------------\n"

. /etc/os-release

if [[ $NAME == *Ubuntu* || $NAME == *Raspbian* ]]; then
    sudo apt install nginx-full curl -y
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    sudo apt install nodejs -y

elif [[ $NAME == *Arch* ]]; then
    sudo pacman -Sy nginx-mainline curl --noconfirm
    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    sudo pacman -Sy nodejs --noconfirm
fi

sudo systemctl stop nginx # in case anything is already loaded
sudo systemctl start nginx
