#!/bin/bash
source ./scripts/make/constants
source /etc/os-release

printf "[+] \e[92mInstalling MMPM GUI Dependencies\e[0m\n"
log_action "Installing MMPM GUI Dependencies"

if [[ $NAME == *Arch* ]]; then
  log_and_eval "sudo pacman -Sy nginx-mainline curl --noconfirm"
  log_and_eval "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"
  log_and_eval "sudo pacman -Sy nodejs --noconfirm >> $MMPM_INSTALLATION_LOG"

elif [[ $NAME == *Ubuntu* || $NAME == *Raspbian* ]]; then
  log_and_eval "sudo apt install nginx-full curl -y"
  log_and_eval "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"
  log_and_eval "sudo apt install nodejs -y"
fi

log_and_eval "sudo systemctl stop nginx"
log_and_eval "sudo systemctl start nginx"

log_action "MMPM GUI Dependencies Installed"
printf "[+] \e[92mInstalled MMPM GUI Dependencies\e[0m\n"
