#!/bin/bash
source ./scripts/make/constants

printf "Installing MMPM GUI Files\n"

log_notice

log_action "Installing MMPM GUI Static Files"

printf " -- copying files to installation destination"
log_and_eval "sudo rm -rvf /var/www/mmpm"
log_and_eval "sudo cp -vr gui/build/* /"
_done_
