#!/bin/bash
source ./scripts/make/constants

printf "Installing MMPM GUI Files\n"

log_notice

log_action "Installing MMPM GUI Static Files"

printf " -- copying files to installation destination"

log_and_eval "tar xvf mmpm-gui-$MMPM_LATEST_VERSION.tar.gz -C mmpm"

_done_
