#!/bin/bash

printf -- "----------------------"
printf "\n| \e[92mRemoving MMPM GUI \e[0m |"
printf "\n----------------------\n"

rm -vf ~/.config/mmpm/configs/gunicorn.conf.py
sudo rm -rvf /var/www/mmpm

printf "\n\033[1;36mMMPM GUI Removed\e[0m\n"
