#!/bin/bash
source ./scripts/make/constants

printf "Removing MMPM GUI\n"

log_notice

log_action "Removing MMPM GUI"

printf " -- removing MMPM GUI configs"
log_and_eval "rm -vf ~/.config/mmpm/configs"
log_and_eval "sudo rm -rvf /var/www/mmpm"
_done_

printf "MMPM GUI Removed\n"
log_action "MMPM GUI Removed"
