name: Nightly MagicMirror Package Download Check

on:
  schedule:
    - cron: "0 0 * * *" # midnight, every night

jobs:
  test:
    runs-on: ubuntu-latest
    container: karsten13/mmpm:latest
    steps:
      - run: mmpm list --all
        name: "Test MMPM package download"
