name: Nightly MagicMirror Package Download Check

on:
  schedule:
    - cron: "0 0 * * *" # midnight, every night

jobs:
  test-mmpm-nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.19
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: "Test MMPM download"
        run: |
          uv pip install mmpm
          uv run mmpm list --all
